export const TYPEORM_TOKENS = {
    USER_REPOSITORY: Symbol.for('USER_REPOSITORY'),
    ROLES_REPOSIOTRY: Symbol.for('ROLES_REPOSIOTRY'),
    USER_PERMISSION_REPOSIOTRY: Symbol.for('USER_PERMISSION_REPOSIOTRY'),
    PRODUCT_REPOSITORY: Symbol.for('PRODUCT_REPOSITORY'),
    ORDER_REPOSITORY: Symbol.for('ORDER_REPOSITORY'),
    PRODUCTS_IMAGE_REPOSITORY : Symbol.for('PRODUCTS_IMAGE_REPOSITORY'),
    PRODUCTS_CATEGORIE_REPORITORY : Symbol.for(' PRODUCTS_CATEGORIE_REPORITORY')
} as const;
